---
deployment:
  tasks:
    - export DEPLOYPATH=/home/chni5636/androne.dev/papillonnotifications
    - /bin/cp -R . $DEPLOYPATH
    # change const API_NOTIFICATIONS_URL = "http://localhost:3000"; to const API_NOTIFICATIONS_URL = "https://pronotepush.androne.dev/"; 
    # in $DEPLOYPATH/notificationsService.js
    - sed -i 's/http:\/\/localhost:3000/https:\/\/pronotepush.androne.dev/g' $DEPLOYPATH/notificationsService.js
    - chmod -R 777 $DEPLOYPATH
